### ISSUE TITLE
Add Theme Section

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/breeze-website#11]
- This section should include this video embeded in full https://www.youtube.com/watch?v=iu-hWvVapbM 
- Make it autoplay
- Bonus :cake: for autoplaying only on non-mobile devices.

**Comment by FlameFractal** [comment]
Two ways to go about it:
- Youtube embed
- Embed video directly

My take on this would be youtube embed, although the initial UI of the player doesn't look nice but it's only there for 1-2 seconds till the video loads. 
And plus, people might go to our channel and look through other content. Or subscribe. So +1 for that right.

Also, as it turns out, youtube embed doesn't autoplay on mobile devices !

**Comment by mr-karan** [comment]
+1 for Youtube embed.
